// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, SmartMemory, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  IDEA_MEMORY: SmartMemory;
  IDEAS_DB: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  MONGODB_URI: string;
  RAINDROP_API_KEY: string;
  tracer: Tracer;
}
